#undef RGBLED_NUM
#undef RGBLIGHT_HUE_STEP
#undef RGBLIGHT_ANIMATIONS

#define RGBLIGHT_EFFECT_STATIC_LIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_TWINKLE

#define RGBLED_NUM 11
#define RGBLIGHT_HUE_STEP 20